// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include <stddef.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "def_nn_kws.h"

extern const int16_t stft_win_coeff[];

extern const int16_t filter_banks[];


PARAMS_NNSP params_nn_kws = {
    .samplingRate = 16000,
    .fftsize = 512,
    .winsize_stft = 480,
    .hopsize_stft = 160,
    .num_mfltrBank = 40,
    .num_dnsmpl = 1,
    .pt_stft_win_coeff = stft_win_coeff,
    .p_melBanks = filter_banks,
    .start_bin = 0,
    .is_dcrm = 1,
    .pre_gain_q1 = 2, // q1
    .feature_type = feat_mel,
};


/*************stats***********/
const int32_t feature_mean_kws[] = {
    0xFFFEF9DF, 0xFFFF60C6, 0xFFFF9ED8, 0xFFFFAF4B, 0xFFFFA370, 0xFFFF9121, 0xFFFF8BA2, 0xFFFF86F4,
    0xFFFF8F68, 0xFFFF80DF, 0xFFFF6C57, 0xFFFF69B4, 0xFFFF5866, 0xFFFF4A5E, 0xFFFF49C8, 0xFFFF497C,
    0xFFFF403A, 0xFFFF39CB, 0xFFFF3C38, 0xFFFF3A46, 0xFFFF2F5E, 0xFFFF2596, 0xFFFF21BD, 0xFFFF21AB,
    0xFFFF20B9, 0xFFFF1D74, 0xFFFF1876, 0xFFFF0F98, 0xFFFF09DA, 0xFFFF0860, 0xFFFEFFB2, 0xFFFEF95A,
    0xFFFEEE49, 0xFFFEE322, 0xFFFEDC2D, 0xFFFED520, 0xFFFED25D, 0xFFFECECF, 0xFFFEC84D, 0xFFFEB432
};

const int32_t feature_stdR_kws[] = {
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF
};
