site_name: SoundKit
repo_url: https://github.com/AmbiqAI/soundkit
theme:
  name: material
  logo: assets/logo.png  # optional
  favicon: assets/favicon.ico  # optional
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tasks:
      - SE:
        - Overview: tasks/se.md
        - Introduction: tasks/se_docs/introduction.md
        - Data: tasks/se_docs/data.md
        - Train: tasks/se_docs/train.md
        - Evaluate: tasks/se_docs/evaluate.md
        - Export: tasks/se_docs/export.md
        - Demo: tasks/se_docs/demo.md

      - VAD:
        - Overview: tasks/vad.md
        - Introduction: tasks/vad_docs/introduction.md
        - Data: tasks/vad_docs/data.md
        - Train: tasks/vad_docs/train.md
        - Evaluate: tasks/vad_docs/evaluate.md
        - Export: tasks/vad_docs/export.md
        - Demo: tasks/vad_docs/demo.md

      - KWS: tasks/kws.md
  - Datasets:
      - Corpora: datasets/corpora.md
      - BYOD: datasets/byod.md
  - models:
      - CRNN: models/crnn.md
      - UNet: models/unet.md
      - BYOM: models/byom.md
  - Loss Functions: loss.md

markdown_extensions:
  - admonition
  - pymdownx.details  # needed for ??? collapsible
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight
  - codehilite


extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js