site_name: soundKIT
site_url: https://ambiqai.github.io/soundkit/
repo_url: https://github.com/AmbiqAI/soundkit
copyright: Copyright &copy; 2025 Ambiq

theme:
  name: material
  logo: assets/logo-white.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
      repo: fontawesome/brands/github-alt
  features:
    - content.code.copy
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Tasks:
      - SE:
        - Overview: tasks/se.md
        - Introduction: tasks/se_docs/introduction.md
        - Data: tasks/se_docs/data.md
        - Train: tasks/se_docs/train.md
        - Evaluate: tasks/se_docs/evaluate.md
        - Export: tasks/se_docs/export.md
        - Demo: tasks/se_docs/demo.md

      - VAD:
        - Overview: tasks/vad.md
        - Introduction: tasks/vad_docs/introduction.md
        - Data: tasks/vad_docs/data.md
        - Train: tasks/vad_docs/train.md
        - Evaluate: tasks/vad_docs/evaluate.md
        - Export: tasks/vad_docs/export.md
        - Demo: tasks/vad_docs/demo.md

      - KWS:
        - Overview: tasks/kws.md
        - Introduction: tasks/kws_docs/introduction.md
        - Data: tasks/kws_docs/data.md
        - Train: tasks/kws_docs/train.md
        - Evaluate: tasks/kws_docs/evaluate.md
        - Export: tasks/kws_docs/export.md
        - Demo: tasks/kws_docs/demo.md
      - ID:
        - Overview: tasks/id.md
        - Introduction: tasks/id_docs/introduction.md
        - Data: tasks/id_docs/data.md
        - Train: tasks/id_docs/train.md
        - Evaluate: tasks/id_docs/evaluate.md
        - Export: tasks/id_docs/export.md
        - Demo: tasks/id_docs/demo.md
      - Troubleshooting: tasks/troubleshooting.md
  - Datasets:
      - Corpora: datasets/corpora.md
      - BYOD: datasets/byod.md
  - models:
      - CRNN: models/crnn.md
      - UNet: models/unet.md
      - BYOM: models/byom.md
  - Loss Functions: loss.md
  - Notebooks:
      - KWS Tutorial: notebooks/SoundKit_KWS_Tutorial.ipynb
      - SE Tutorial: notebooks/SoundKit_SE_Tutorial.ipynb
      - VAD Tutorial: notebooks/SoundKit_VAD_Tutorial.ipynb
  - Dashboards:
      - ID USB Dashboard: web-dashboards/id-usb/index.html
      - NNSE USB Dashboard: web-dashboards/nnse-usb/index.html
      - SD USB Dashboard: web-dashboards/sd-usb/index.html
markdown_extensions:
  - admonition
  - pymdownx.details  # needed for ??? collapsible
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.highlight
  - codehilite

plugins:
  - search
  - mkdocs-jupyter:
      include_requirejs: true
      include_source: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/custom.css
