name: cnn2d_cnn
project: vad
job_dir: ./soundkit/tasks/vad

data:
  path_tfrecord: ${job_dir}/tfrecords
  tfrecord_datalist_name: # list of saved tfrecords
    train: train_tfrecord.csv 
    val: val_tfrecord.csv
  num_samples_per_noise:
    train: 1000
    val: 250
  force_download: false
  reverb_prob: 0.2
  num_processes: 8
  corpora:
    - {name: vad_train-clean-100, type: speech, split: train}
    - {name: vad_train-clean-360, type: speech, split: train}
    - {name: vad_dev-clean, type: speech, split: val}
    - {name: vad_thchs30, type: speech, split: train-val}
    - {name: ESC-50-master, type: noise, split: train-val}
    - {name: FSD50K, type: noise, split: train-val}
    - {name: musan, type: noise, split: train-val}
    - {name: wham_noise, type: noise, split: train-val}
    - {name: rirs_noises, type: reverb, split: train-val}
    
  snr_dbs: [-6, -3, 0, 3, 6, 9, 12, 15, 30] # mixture of signal-to-noise ratios
  target_length_in_secs: 15
  min_amp: 0.01
  max_amp: 0.95

  signal:
    sampling_rate: 16000
    dc_removal: false
  debug: false

train:
  initial_lr: 4e-4
  batchsize: 100
  epochs: 200
  warmup_epochs: 5
  epoch_loaded: random
  loss_function: 
    # type: focal
    # params: {gamma: 2.0, alpha: 0.75} # for focal loss
    type: cross_entropy
    params: {}
    
  path:
    checkpoint_dir:  ${job_dir}/models_trained/${name}_${train.loss_function.type}
    tensorboard_dir: ${job_dir}/tensorboard/${name}_${train.loss_function.type}
  num_lookahead: 0
  spec_aug: false

  feature:
    frame_size: 160
    hop_size: 160
    fft_size: 512
    type: time

    # type: hybrid
    # bins_fft: 100
    # n_mels: 72

  standardization: false
  
  model:
    config_dir: ./soundkit/models/arch_configs
    config_file: config_cnn2d_vad.yaml
    override:
      dropout: 0.2
      rnn_res: false
      normalization_layer:
      dim_out_rnn: 64
      activation: relu
      channels: [1, 32, 32, 32, 32]
      kernel_sizes: [[1,5], [1,5], [1,5], [1,5]]
      time_net: tcn
      kernel_size_tcn: 2
      filters_tcn: 32
      dilations: [1, 2, 4, 8, 16, 32]
  reset_states_every_batch: true
  debug: false

evaluate:
  epoch_loaded: best

  data: 
    dir: "./wavs/vad/test_wavs"
    files: [speech.wav, speech_pubNoise.wav]
    result_folder: ${job_dir}/test_results/${name}_${train.loss_function.type}

export:
  dtype: int16
  eval: true
  qbit_input: 15
  epoch_loaded: best
  tflite_dir: ${job_dir}/tflite_${export.dtype}

demo:
  platform: pc # evb or pc
  epoch_loaded: best
  tflite_dir: ${job_dir}/tflite
  evb_dir: ${job_dir}/evb
  pre_gain: 1
  dtype: int16
  filename: def_nn1_nnvad
  param_struct_name: params_nn1_nnvad
