// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include <stddef.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "def_nn2_nnid.h"

extern const int16_t stft_win_coeff[];

extern const int16_t filter_banks[];


PARAMS_NNSP params_def_nn2_nnid = {
    .samplingRate = 16000,
    .fftsize = 512,
    .winsize_stft = 480,
    .hopsize_stft = 160,
    .num_mfltrBank = 40,
    .num_dnsmpl = 1,
    .pt_stft_win_coeff = stft_win_coeff,
    .p_melBanks = filter_banks,
    .start_bin = 0,
    .is_dcrm = 1,
    .pre_gain_q1 = 2, // q1
    .feature_type = feat_mel,
};


/*************stats***********/
const int32_t feature_mean_id[] = {
    0xFFFF32DA, 0xFFFFA445, 0xFFFFF613, 0x000018B6, 0x000009A5, 0xFFFFF526, 0xFFFFF3F7, 0xFFFFEDE0,
    0xFFFFF045, 0xFFFFD9DB, 0xFFFFBB0C, 0xFFFFB2A9, 0xFFFF9E47, 0xFFFF8D75, 0xFFFF8A8C, 0xFFFF89BC,
    0xFFFF8297, 0xFFFF7FF1, 0xFFFF867E, 0xFFFF87A7, 0xFFFF7DD8, 0xFFFF7429, 0xFFFF717A, 0xFFFF7378,
    0xFFFF7592, 0xFFFF7236, 0xFFFF6CAF, 0xFFFF6362, 0xFFFF5C9B, 0xFFFF5A68, 0xFFFF5043, 0xFFFF4791,
    0xFFFF3A72, 0xFFFF2CA2, 0xFFFF235F, 0xFFFF19FE, 0xFFFF1656, 0xFFFF11F3, 0xFFFF099B, 0xFFFEFAFD
};

const int32_t feature_stdR_id[] = {
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF
};
