// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "def_nn2_nnid.h"

extern const int16_t stft_win_coeff[];

extern const int16_t filter_banks[];

PARAMS_NNSP params_def_nn2_nnid = {
    .samplingRate = 16000,
    .fftsize = 512,
    .winsize_stft = 480,
    .hopsize_stft = 160,
    .num_mfltrBank = 40,
    .num_dnsmpl = 1,
    .pt_stft_win_coeff = stft_win_coeff,
    .p_melBanks = filter_banks,
    .start_bin = 0,
    .is_dcrm = 1,
    .pre_gain_q1 = 2, // q1
};


/*************stats***********/
const int32_t feature_mean_id[] = {
    0xFFFF3453, 0xFFFFA583, 0xFFFFF6E1, 0x0000198D, 0x00000AF8, 0xFFFFF5F1, 0xFFFFF4CC, 0xFFFFEEE1,
    0xFFFFF130, 0xFFFFDAE7, 0xFFFFBC83, 0xFFFFB41C, 0xFFFF9FBB, 0xFFFF8F05, 0xFFFF8C22, 0xFFFF8B43,
    0xFFFF840B, 0xFFFF8187, 0xFFFF87CF, 0xFFFF88E8, 0xFFFF7F35, 0xFFFF7590, 0xFFFF72F2, 0xFFFF74BF,
    0xFFFF76BA, 0xFFFF7377, 0xFFFF6DD2, 0xFFFF646B, 0xFFFF5DB6, 0xFFFF5B8D, 0xFFFF515A, 0xFFFF48AF,
    0xFFFF3BDB, 0xFFFF2E4A, 0xFFFF2517, 0xFFFF1B98, 0xFFFF17F6, 0xFFFF13D1, 0xFFFF0B73, 0xFFFEFC8C
};

const int32_t feature_stdR_id[] = {
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF
};
