// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include <stddef.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "def_nn2_nnid.h"

extern const int16_t stft_win_coeff[];

extern const int16_t filter_banks[];


PARAMS_NNSP params_def_nn2_nnid = {
    .samplingRate = 16000,
    .fftsize = 512,
    .winsize_stft = 480,
    .hopsize_stft = 160,
    .num_mfltrBank = 40,
    .num_dnsmpl = 1,
    .pt_stft_win_coeff = stft_win_coeff,
    .p_melBanks = filter_banks,
    .start_bin = 0,
    .is_dcrm = 1,
    .pre_gain_q1 = 2, // q1
    .feature_type = feat_mel,
};


/*************stats***********/
const int32_t feature_mean_id[] = {
    0xFFFF3478, 0xFFFFA586, 0xFFFFF6E8, 0x00001986, 0x00000A93, 0xFFFFF5DE, 0xFFFFF517, 0xFFFFEF34,
    0xFFFFF17D, 0xFFFFDB53, 0xFFFFBD1B, 0xFFFFB4FC, 0xFFFFA0A6, 0xFFFF9014, 0xFFFF8D4A, 0xFFFF8C58,
    0xFFFF8519, 0xFFFF828B, 0xFFFF88EF, 0xFFFF8A08, 0xFFFF8052, 0xFFFF769E, 0xFFFF740E, 0xFFFF75EA,
    0xFFFF7819, 0xFFFF74E0, 0xFFFF6F57, 0xFFFF65EE, 0xFFFF5F29, 0xFFFF5D18, 0xFFFF5322, 0xFFFF4A78,
    0xFFFF3D52, 0xFFFF2F8C, 0xFFFF2664, 0xFFFF1CDE, 0xFFFF1904, 0xFFFF14CA, 0xFFFF0C96, 0xFFFEFDEE
};

const int32_t feature_stdR_id[] = {
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF,
    0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF, 0x00007FFF
};
