name: se_ch8_exp06_sep_moredata
project: se
job_dir: ./soundkit/tasks/se

data:
  path_tfrecord: ./soundkit/tasks/se/tfrecords_wind
  tfrecord_datalist_name: # list of saved tfrecords
    train: train_tfrecord_wind.csv 
    val: val_tfrecord_wind.csv
  num_samples_per_noise:
    train: 600000
    val: 2000
  force_download: false
  reverb_prob: 0.2

  num_processes: 8
  corpora:
    - {name: train-clean-360, type: speech, split: train}
    - {name: train-clean-100, type: speech, split: train}
    - {name: dev-clean, type: speech, split: val,}
    - {name: thchs30, type: speech, split: train-val}
    # - {name: ESC-50-master, type: noise, split: train-val}
    # - {name: FSD50K, type: noise, split: train-val}
    # - {name: musan, type: noise, split: train-val}
    # - {name: wham_noise, type: noise, split: train-val}
    # - {name: dns_challenge, type: noise, split: train-val}
    - {name: wind_noise, type: noise, split: train-val}
    - {name: rirs_noises, type: reverb, split: train-val}
  snr_dbs: [-9, -6, -3, 0, 3, 6, 9, 12, 15] # mixture of signal-to-noise ratios
  target_length_in_secs: 10.0
  min_amp: 0.03
  max_amp: 0.95

  signal:
    sampling_rate: 16000
    dc_removal: true

  debug: false

train:
  num_per_epoch_files: 
    train: 40000
  truncate_time: 8.0  # in seconds, set to null to use full length
  initial_lr: 4e-4
  lr_schedule: cosine
  batchsize: 32
  epochs: 300
  warmup_epochs: 5
  epoch_loaded: random
  spec_aug: false
  reset_states_every_batch: true
  loss_function:

    # type: si_sdr
    # params: 
    #   exp: 0.6
    #   eps: 1e-8

    type: time_smooth_mae
    params: 
      fft_size: ${train.feature.fft_size}
      frame_size: ${train.feature.frame_size}
      hop_size: ${train.feature.hop_size}
      is_norm: true
      eps: 1e-12
      power_law_exp: 0.6

    # type: compressed_mse
    # params: 
    #   exp: 0.6
    #   eps: 1e-8

    # type: mrl_mse
    # params:
    #   exp: 0.6
    #   eps: 1e-8
    #   fft_size: ${train.feature.fft_size}
    #   hop_size: ${train.feature.hop_size}
    #   frame_size: ${train.feature.frame_size}

    # type: compound_loss
    # params:
    #   losses:
    #     - type: si_sdr
    #       weight: 0.3
    #       params:
    #         eps: 1e-8
    #     - type: mrl_mse
    #       weight: 0.7
    #       params:
    #         exp: 0.6
    #         eps: 1e-8
    #         fft_size: ${train.feature.fft_size}
    #         hop_size: ${train.feature.hop_size}
    #         frame_size: ${train.feature.frame_size}

  path:
    full_name: ${name}_${train.loss_function.type}_${train.feature.type}
    checkpoint_dir: ${job_dir}/models_trained/${train.path.full_name}
    tensorboard_dir: ./soundkit/tasks/se/tensorboard/${train.path.full_name}
  num_lookahead: 2 # the number of future frames to be used. 0: causal, 1: 1-frame lookahead, etc.

  feature: 
    frame_size: 480
    hop_size: 160
    fft_size: 512
    type: erb_complex
    bins: 72
    bins_fft: 64
    n_mels: 72

  standardization: false
  
  model:
     config_dir: ./soundkit/models/arch_configs
     config_file: config_unet_relu_complex_erb.yaml
     override:
       bottleneck: lstm
       separable: true
       output_scaling: 2.0
       num_chs: [2, 8, 8, 8]

  debug: false

evaluate:
  epoch_loaded: 100

  data: 
    dir: "./wavs/se/test_wavs"
    # files: [wind_1_90sec_ch0.wav, wind_2_60sec_ch0.wav, wind_3_240sec_ch0.wav, keyboard_steak.wav, i_like_steak.wav, steak_hairdryer.wav]
    files: [keyboard_steak.wav, i_like_steak.wav, steak_hairdryer.wav]
    result_folder: ${job_dir}/test_results/${train.path.full_name}
export:
  dtype: int16
  qbit_input: 8
  epoch_loaded: random
  tflite_dir: zoo/se/crnn

demo:
  epoch_loaded: best
  platform: evb # or pc
  tflite_dir: ./soundkit/tasks/se/tflite
  evb_dir: ./soundkit/tasks/se/evb
  
  pre_gain: 1
