name: unet_time_test_glu1
project: se2
job_dir: ./soundkit/tasks/se2

data:
  path_tfrecord: ${job_dir}/tfrecords
  tfrecord_datalist_name: # list of saved tfrecords
    train: train_tfrecord.csv 
    val: val_tfrecord.csv
  num_samples_per_noise:
    train: 30000
    val: 3000
  force_download: false
  reverb_prob: 0.2
  num_processes: 8
  corpora:
    - {name: train-clean-360, type: speech, split: train}
    - {name: train-clean-100, type: speech, split: train}
    - {name: dev-clean, type: speech, split: val,}
    - {name: thchs30, type: speech, split: train-val}
    - {name: ESC-50-master, type: noise, split: train-val}
    - {name: FSD50K, type: noise, split: train-val}
    - {name: musan, type: noise, split: train-val}
    - {name: wham_noise, type: noise, split: train-val}
    - {name: rirs_noises, type: reverb, split: train-val}
  snr_dbs: [-6, -3, 0, 3, 6] # mixture of signal-to-noise ratios
  # snr_dbs: [0] # mixture of signal-to-noise ratios
  target_length_in_secs: 5
  min_amp: 0.01
  max_amp: 0.95

  reset_every_batch: true

  signal:
    sampling_rate: 16000
    dc_removal: true
  
  debug: false

train:
  lr_schedule: cosine
  initial_lr: 4e-4
  batchsize: 15
  epochs: 200
  warmup_epochs: 3
  epoch_loaded: random
  loss_function: {
    # type: mse,
    # params:  # Normalized MSE
    # type: compressed_mse,
    # params: {
    #   exp: 0.6,
    #   eps: 1e-8,
    # }
    type: mrl_mse,
    params: {
      exp: 0.6,
      eps: 1e-8,
      input_type: stft,
      fft_size: "${train.feature.fft_size}",
      hop_length: "${train.feature.hop_size}",
      frame_size: "${train.feature.frame_size}"
    }
  }
  path:
    checkpoint_dir: ./soundkit/tasks/se2/models_trained/${name}
    tensorboard_dir: ./soundkit/tasks/se2/tensorboard/${name}

  num_lookahead: 2

  feature: 
    frame_size: 320
    hop_size: 160
    fft_size: 512
    type: time

  reset_every_batch: true
  standardization: false
  
  model:
    config_dir: ./soundkit/models/arch_configs
    config_file: config_unet_time.yaml
    override:
      dim_out: ${train.feature.frame_size}
      dropout: 0.0
      rnn_res: true
      skip_connection_type: concat

  debug: false

evaluate:
  epoch_loaded: best

  data: 
    dir: "./wavs/se/test_wavs"
    files: [ keyboard_steak.wav, i_like_steak.wav, steak_hairdryer.wav]
    result_folder: ${job_dir}/test_results/${name}

export:
  epoch_loaded: best
  tflite_dir: ${job_dir}/tflite

demo:
  epoch_loaded: best
  platform: evb # or pc
  tflite_dir: ${job_dir}/tflite
  evb_dir: ${job_dir}/evb_webusb
  pre_gain: 1
