from pathlib import Path
import numpy as np

def generate_feature_c_files(
    file_name: str,
    param_struct_name: str,
    dir: str,
    feature_mean: np.ndarray,
    feature_std: np.ndarray,
    *,
    sampling_rate: int = 16000,
    fftsize: int = 512,
    winsize_stft: int = 480,
    hopsize_stft: int = 160,
    num_mfltrBank: int = 69,
    num_dnsmpl: int = 1,
    start_bin: int = 0,
    is_dcrm: int = 1,
    pre_gain_q1: int = 2,
    lookahead: int = 1,
    stft_win_coeff_name: str = "stft_win_coeff_w480_h160",
):

    def format_array(name, values, type_name="int32_t"):
        items_per_line = 8
        values = values.flatten()  # 👈 flatten to 1D     
        lines = []
        for i in range(0, len(values), items_per_line):
            line = ", ".join(f"0x{int(val*(2**15)) & 0xFFFFFFFF:08x}" for val in values[i:i + items_per_line])
            lines.append(line)
        array_body = ",\n    ".join(lines)
        return f"const {type_name} {name}[] = {{\n    {array_body}\n}};"


    # === Generate .c file
    c_code = f"""// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "{file_name}.h"

extern const int16_t {stft_win_coeff_name}[];

PARAMS_NNSP {param_struct_name} = {{
    .samplingRate = {sampling_rate},
    .fftsize = {fftsize},
    .winsize_stft = {winsize_stft},
    .hopsize_stft = {hopsize_stft},
    .num_mfltrBank = {num_mfltrBank},
    .num_dnsmpl = {num_dnsmpl},
    .pt_stft_win_coeff = {stft_win_coeff_name},
    .start_bin = {start_bin},
    .is_dcrm = {is_dcrm},
    .pre_gain_q1 = {pre_gain_q1}, // q1
}};

/*************stats***********/
{format_array("feature_mean_se", feature_mean)}

{format_array("feature_stdR_se", feature_std)}
"""
    Path(f"{dir}/{file_name}.c").write_text(c_code)
    print(f"✅ Wrote {file_name}.c")

    # === Generate .h file
    h_code = f"""#ifndef __DEF_NN3_SE__
#define __DEF_NN3_SE__

#include <stdint.h>
#include "neural_nets.h"
#include "nn_speech.h"

extern const int32_t feature_mean_se[];
extern const int32_t feature_stdR_se[];

#define NUM_LOOKAHEAD {lookahead}
extern PARAMS_NNSP {param_struct_name};

#endif  // __DEF_NN3_SE__
"""
    Path(f"{dir}/{file_name}.h").write_text(h_code)
    print(f"✅ Wrote {file_name}.h")
