// auto-generated by generate_nn_c_files
// arm_core = cortex-M55
#include <stdint.h>
#include <stddef.h>
#include "neural_nets.h"
#include "activation.h"
#include "affine.h"
#include "lstm.h"
#include "nn_speech.h"
#include "def_nn3_se.h"

extern const int16_t stft_win_coeff[];

extern const int16_t filter_banks[];


PARAMS_NNSP params_nn3_se = {
    .samplingRate = 16000,
    .fftsize = 512,
    .winsize_stft = 480,
    .hopsize_stft = 160,
    .num_mfltrBank = 72,
    .num_dnsmpl = 1,
    .pt_stft_win_coeff = stft_win_coeff,
    .p_melBanks = filter_banks,
    .start_bin = 0,
    .is_dcrm = 1,
    .pre_gain_q1 = 2, // q1
    .feature_type = feat_mel,
};


/*************stats***********/
const int32_t *feature_mean_se = NULL;

const int32_t *feature_stdR_se = NULL;
