name: crnn
project: se
job_dir: ./soundkit/tasks/se

data:
  debug: False
  path_tfrecord: ./soundkit/tasks/se/tfrecords
  tfrecord_datalist_name: # list of saved tfrecords
    train: train_tfrecord.csv 
    test: test_tfrecord.csv
  num_samples_per_noise:
    train: 1000
    test: 250
  force_download: False
  reverb_prob: 1.0
  num_processes: 8
  corpora:
    - {name: train-clean-360, type: train, path: wavs/LibriSpeech/train-clean-360}
    - {name: train-clean-100, type: train, path: wavs/LibriSpeech/train-clean-100}
    - {name: thchs30, type: train-dev, path: {train: wavs/data_thchs30/train, dev: wavs/data_thchs30/dev}}
    - {name: dev-clean, type: dev, path: wavs/LibriSpeech/dev-clean}
    - {name: ESC-50-master, type: noise}
    - {name: FSD50K, type: noise}
    - {name: musan, type: noise}
    - {name: wham_noise, type: noise}
    - {name: rirs_noises, type: reverb}
  snr_dbs: [-6, -3, 0, 3, 6, 9, 12, 15, 30] # mixture of signal-to-noise ratios
  # snr_dbs: [100] # mixture of signal-to-noise ratios
  target_length_in_secs: 5
  min_amp: 0.01
  max_amp: 0.95

  signal:
    sampling_rate: 16000
    frame_size: 480
    hop_size: 160
    fft_size: 512
    dc_removal: True
    feature: {type: mel, bins: 72}

train:
  initial_lr: 4e-4
  batchsize: 128
  epochs: 150
  warmup_epochs: 5
  epoch_loaded: random
  loss_function: {type: mse, params: 0.6}
  path:
    models_trained: ./soundkit/tasks/se/models_trained
    tensorboard: ./soundkit/tasks/se/tensorboard
  num_lookahead: 2
  standardization: True
  
  model:
    name: CRNN
    config_path: ./soundkit/models/configs/config_crnn.yaml
    