name: crnn
units: 100
len_time: 6
layer_configs:
  - type: dropout
    rate: 0.0

  - type: conv2d
    filters: ${units}
    kernel_size: ["${len_time}", 72]
    strides: [1, 1]
    activation: relu

  - type: dropout
    rate: 0.0

  - type: lstm
    units: ${units}

  - type: dropout
    rate: 0.0

  - type: fc
    units: ${units}
    activation: relu

  - type: dropout
    rate: 0.0

  - type: fc
    units: ${units}
    activation: relu

  - type: dropout
    rate: 0.0

  - type: fc
    units: 257
    activation: sigmoid
