name: conv_lstm_hybrid
units: 100
len_time: 6
layer_configs:
  - type: dropout
    rate: 0.1

  - type: conv2d
    filters: ${units}
    kernel_size: ["${len_time}", 40]
    strides: [1, 1]
    activation: tanh

  - type: dropout
    rate: 0.25

  - type: lstm
    units: ${units}

  - type: dropout
    rate: 0.25

  - type: fc
    units: ${units}
    activation: tanh

  - type: dropout
    rate: 0.25

  - type: fc
    units: 64
    activation: linear
